### ISSUE TITLE
R.id.chat_container NOT FOUND!

### ISSUE THREAD

**Issue by UmerTaptap** [MyPureCloud/mobiledx-samples-android#102]
`ChatController.Builder(context).build(account, object : ChatLoadedListener {
    override fun onComplete(result: ChatLoadResponse) {
        result.error?.let {
            // report Chat loading failed
        } ?: let {
            // add result.fragment to your activity.
            supportFragmentManager.beginTransaction().replace(R.id.chat_container, result.fragment, tag).commit()
        }
    }
})`

I just copied this code snippet,  getting error in " supportFragmentManager.beginTransaction().replace(R.id.chat_container, result.fragment, tag).commit()" line, saying "Unresolved reference: chat_container". What i should do?

**Comment by mobichel** [comment]
Dear @UmerTaptap ,

Thank you for reaching out about the error you're encountering with the ChatController code snippet.

The error "Unresolved reference: chat_container" typically occurs when the layout resource `ID R.id.chat_container` is not defined in your layout XML file.

To fix this, you need to ensure that you have a container view in your layout with the ID "chat_container". Here are the steps to resolve this:

- Open your layout XML file (e.g., activity_main.xml or whatever layout file you're using for this activity).
- Add a container view (like a FrameLayout) to host your chat fragment. For example:
```
<FrameLayout
    android:id="@+id/chat_container"
    android:layout_width="match_parent"
    android:layout_height="match_parent" />
```
- Make sure this container is placed appropriately within your layout hierarchy.
- After adding the container, rebuild your project to ensure it's working correctly.

Don't hesitate to use our [forms](https://developer.genesys.cloud/forum/c/web-messaging/39) for your future questions.

**Comment by mobichel** [comment]
Closing the issue since documentation has been updated: https://developer.genesys.cloud/commdigital/digital/webmessaging/mobile-messaging/messenger-mobile-sdk/android/#3--display-the-messenger-ui-component-in-your-application
